---
- name: Install AWS CloudWatch, SSM Agent, AWS Inspector, and Docker
  hosts: your_target_group
  become: true  # Run tasks as sudo

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - docker.io
        - unzip

    - name: Install AWS CloudWatch Agent
      shell: |
        wget https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb
        dpkg -i amazon-cloudwatch-agent.deb
      args:
        creates: /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent

    - name: Install AWS SSM Agent
      shell: |
        wget https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/debian_amd64/amazon-ssm-agent.deb
        dpkg -i amazon-ssm-agent.deb
      args:
        creates: /usr/bin/amazon-ssm-agent

    - name: Install AWS Inspector Agent
      shell: |
        curl -O https://inspector-agent.amazonaws.com/linux/latest/install
        bash install
      args:
        creates: /opt/aws/awsagent

    - name: Start Docker Service
      service:
        name: docker
        state: started
        enabled: yes

    
